config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('products.urls', namespace='products'))
]

products/urls.py
from django.urls import path

from products.apps import ProductsConfig
from products.views import get_stripe_session_id, item_detail, order_payment, toggle_item, create_order

app_name = ProductsConfig.name

urlpatterns = [
    path('buy/<int:pk>/', get_stripe_session_id, name='buy-item'),
    path('order/create', create_order, name='create_order'),
    path('order/payment', order_payment, name='payment_order'),
    path('item/<int:pk>/', item_detail, name='item-page'),
    path('toggle_item/<int:item_pk>/', toggle_item, name='add_and_delete_item'),
]

products/models.py
from django.db import models
from django.utils.translation import gettext_lazy as _

NULLABLE = {'null': True, "blank": True}


class Currency(models.TextChoices):
    USD = 'USD', _('USD')
    RUB = 'RUB', _('RUB')


class Item(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    description = models.TextField(verbose_name='описание')
    price = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='цена')
    currency = models.CharField(max_length=3, choices=Currency.choices, default=Currency.USD, verbose_name='валюта')

    def __str__(self):
        return f'{self.name} = {self.price}'

    class Meta:
        verbose_name = 'Продукт'
        verbose_name_plural = 'Продукты'


class Discount(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    amount = models.DecimalField(max_digits=10, decimal_places=2, verbose_name='сумма')

    def __str__(self):
        return f'{self.name}/ {self.amount}'

    class Meta:
        verbose_name = 'Скидка'
        verbose_name_plural = 'Скидки'


class Tax(models.Model):
    name = models.CharField(max_length=100, verbose_name='наименование')
    rate = models.DecimalField(max_digits=5, decimal_places=2, verbose_name='ставка')

    def __str__(self):
        return f'{self.name}/ {self.rate}'

    class Meta:
        verbose_name = 'Налог'
        verbose_name_plural = 'Налоги'


class Order(models.Model):
    items = models.ManyToManyField(Item, related_name='orders', verbose_name='продукт')
    discount = models.ForeignKey(Discount, on_delete=models.SET_NULL, **NULLABLE, verbose_name='скидка')
    tax = models.ForeignKey(Tax, on_delete=models.SET_NULL, **NULLABLE, verbose_name='налог')
    total_amount = models.DecimalField(max_digits=10, default=0, decimal_places=2, verbose_name='общая сумма')
    currency = models.CharField(max_length=3, choices=Currency.choices, default=Currency.USD, verbose_name='валюта')

    def calculate_total_amount(self):
        total = sum(item.price for item in self.items.all())
        if self.discount:
            total -= self.discount.amount
        if self.tax:
            total *= (1 + self.tax.rate / 100)
        return total

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        self.total_amount = self.calculate_total_amount()
        super().save(update_fields=['total_amount'])

    def __str__(self):
        return f"Order #{self.id}"

    class Meta:
        verbose_name = 'Заказ'
        verbose_name_plural = 'Заказы'

products/forms.py
from django import forms

from products.models import Order


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if field_name != "available":
                field.widget.attrs['class'] = 'form-control'


class OrderForm(StyleFormMixin, forms.ModelForm):
    class Meta:
        model = Order
        fields = "__all__"
        exclude = ('total_amount', 'items')

products/views.py
import json

import stripe
from django.http import JsonResponse, HttpResponseBadRequest
from django.shortcuts import get_object_or_404, render
from django.views.decorators.csrf import csrf_exempt

from config.settings import STRIPE_SECRET_KEY, STRIPE_PUBLIC_KEY
from products.forms import OrderForm
from products.models import Item, Order

stripe.api_key = STRIPE_SECRET_KEY


@csrf_exempt
def get_stripe_session_id(request, pk):
    item = get_object_or_404(Item, id=pk)
    try:
        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': item.currency,
                    'product_data': {
                        'name': item.name,
                        'description': item.description,
                    },
                    'unit_amount': int(item.price * 100),
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url='http://127.0.0.1:8000/',
            cancel_url='http://127.0.0.1:8000/',
        )
        return JsonResponse({'session_id': session.id})
    except Exception as e:
        return HttpResponseBadRequest(json.dumps({'error': str(e)}), content_type='application/json')


def item_detail(request, pk):
    item = get_object_or_404(Item, id=pk)
    context = {
        'item': item,
        'STRIPE_PUBLIC_KEY': STRIPE_PUBLIC_KEY
    }
    return render(request, 'products/item_detail.html', context)


@csrf_exempt
def create_order(request):
    try:
        order = Order.objects.first()
        if order is None:
            order = Order.objects.create()

        if request.method == 'POST':
            form = OrderForm(request.POST, instance=order)
            if form.is_valid():
                form.save()
                total_amount = order.calculate_total_amount()
                return JsonResponse({'total_amount': total_amount})
        else:
            form = OrderForm(instance=order)

        return render(request, 'products/create_order.html', {'form': form, 'order': order,
                                                              'products': Item.objects.all(),
                                                              'STRIPE_PUBLIC_KEY': STRIPE_PUBLIC_KEY})

    except Exception as e:
        return JsonResponse({'error': str(e)}, status=400)


@csrf_exempt
def order_payment(request):
    try:
        order = Order.objects.first()
        if order is None:
            order = Order.objects.create()

        total_amount = order.calculate_total_amount()

        session = stripe.checkout.Session.create(
            payment_method_types=['card'],
            line_items=[{
                'price_data': {
                    'currency': order.currency,
                    'product_data': {
                        'name': 'Order #{}'.format(order.id),
                        'description': 'Payment for order #{}'.format(order.id),
                    },
                    'unit_amount': int(total_amount * 100),
                },
                'quantity': 1,
            }],
            mode='payment',
            success_url='http://127.0.0.1:8000/',
            cancel_url='http://127.0.0.1:8000/',
            metadata={
                'tax_amount': order.tax,
                'discount_amount': order.discount,
            }
        )
        return JsonResponse({'session_id': session.id})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=400)


def toggle_item(request, item_pk):
    try:
        order = Order.objects.first()
        item = Item.objects.get(pk=item_pk)

        if item in order.items.all():
            order.items.remove(item)
        else:
            order.items.add(item)

        total_amount = order.calculate_total_amount()

        return JsonResponse({'total_amount': total_amount})
    except Exception as e:
        return JsonResponse({'error': str(e)}, status=400)

products/templates/products/base.html
{% load static %}
<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>{{ title }}</title>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
</head>
<body>
<div class="container mt-4">

    {% block content %}
    {% endblock %}

    <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
        </div>
    </footer>
</div>

<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
</body>
</html>

products/templates/products/create_order.html
{% extends 'products/base.html' %}

{% block content %}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title>Создание заказа</title>
        <script src="https://js.stripe.com/v3/"></script>
    </head>
    <body>
    <h1>Создание заказа</h1>
    <form id="order-form" method="post" action="{% url 'products:create_order' %}">
        {% csrf_token %}
        {{ form.as_p }}

        <ul>
            <h4>Список продуктов:</h4>
            {% for product in products %}
                <li>
                    <input type="checkbox" id="product_{{ product.id }}" name="items" value="{{ product.id }}"
                           {% if product in order.items.all %}checked{% endif %}>
                    <label for="product_{{ product.id }}">{{ product.name }}</label>
                </li>
            {% endfor %}
        </ul>

        <p>Общая сумма: <span id="total-amount">{{ order.total_amount }} {{ order.currency }}</span></p>

        <input type="hidden" name="session_id" id="session_id" value="{{ session_id }}">

        <input type="submit" id="save-order-btn" value="Сохранить заказ">
    </form>

    <form id="payment-form" method="get" action="{% url 'products:payment_order' %}">
        <input type="submit" value="Оплатить заказ">
    </form>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const form = document.getElementById('order-form');
            const saveButton = document.getElementById('save-order-btn');
            const paymentForm = document.getElementById('payment-form');

            saveButton.addEventListener('click', function (event) {
                event.preventDefault();
                fetch(form.action, {
                    method: 'POST',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                    },
                    body: new FormData(form)
                })
                    .then(response => response.json())
                    .then(data => {
                        alert('Заказ успешно сохранен!');
                    })
                    .catch(error => console.error('Error:', error));
            });

            paymentForm.addEventListener('submit', function (event) {
                event.preventDefault();
                fetch(paymentForm.action, {
                    method: 'GET',
                    headers: {
                        'X-CSRFToken': '{{ csrf_token }}',
                    }
                })
                    .then(response => response.json())
                    .then(data => {
                        const stripe = Stripe('{{ STRIPE_PUBLIC_KEY }}');
                        stripe.redirectToCheckout({sessionId: data.session_id})
                            .then(function (result) {
                                if (result.error) {
                                    console.error(result.error.message);
                                }
                            });
                    })
                    .catch(error => console.error('Error:', error));
            });

            const checkboxes = document.querySelectorAll('input[name="items"]');
            const totalAmountField = document.querySelector('#total-amount');

            checkboxes.forEach(function (checkbox) {
                checkbox.addEventListener('change', function () {
                    fetch('/toggle_item/' + this.value + '/', {
                        method: 'POST',
                        headers: {
                            'X-CSRFToken': '{{ csrf_token }}',
                        },
                    })
                        .then(response => response.json())
                        .then(data => {
                            totalAmountField.textContent = data.total_amount;
                        })
                        .catch(error => {
                            console.error('Error:', error);
                        });
                });
            });
        });
    </script>
    </body>
{% endblock %}

products/templates/products/item_detail.html
{% extends 'products/base.html' %}

{% block content %}
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>{{ item.name }}</title>
    </head>
    <h1>{{ item.name }}</h1>
    <p>{{ item.description }}</p>
    <p>Price: {{ item.price }} {{ item.currency }}</p>
    <button id="buy-btn" type="button">Купить</button>

    <script src="https://js.stripe.com/v3/"></script>
    <script type="text/javascript">
        document.getElementById('buy-btn').addEventListener('click', function () {
            fetch(`/buy/{{ item.id }}`)
                .then(response => {
                    if (!response.ok) {
                        throw new Error('Network response was not ok');
                    }
                    return response.json();
                })
                .then(data => {
                    const stripe = Stripe('{{ STRIPE_PUBLIC_KEY }}');
                    stripe.redirectToCheckout({sessionId: data.session_id})
                        .then(function (result) {
                            if (result.error) {
                                console.error(result.error.message);
                            }
                        });
                })
                .catch(error => console.error('Error:', error));
        });
    </script>
{% endblock %}